### ISSUE TITLE
Cannot get module to work: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by sbarli** [ebuzek/vue-object-view#4]
I've tried to import this module into three different projects all running Vue 2.5.3 and keep getting this error.

I've tried using the same example data from the demo app (https://github.com/ebuzek/vue-object-view-demo), but it still doesn't work.

Not sure what I could be doing wrong.  Code currently looks like this:

```
<template>
  <div>
   <h1>{{ msg }}</h1>
   <VueObjectView v-model="object1" />
  </div>
</template>
 
 <script>
 import VueObjectView from 'vue-object-view';

let string = "This is a string";
let boolean = true;
let _null = null;
let _undefined = undefined;
let number = 3.14;

let object1 = {
  string,
  boolean,
  "null": null,
  "undefined" : undefined,
  number
}

export default {
  data() {
    return {
      msg: "Hello Sam",
      object1
    };
  },
  computed: {
    clientState() {
      return this.$store.state.clientState;
    }
  },
  components: {
    VueObjectView
  }
};
</script>
```

**Comment by ebuzek** [comment]
There were breaking changes in `vue-loader` v13.0.0, notably changes in loading circular components: [Circular references between components broken after upgrading vue-loader to 13.x #933](https://github.com/vuejs/vue-loader/issues/933)

Second, component property type validation probably changed as well...

Both issues are fixed in **v0.4.2** and the component should work with newest version of vue/vue-loader now.

Your working example is here:
[test.zip](https://github.com/ebuzek/vue-object-view/files/1443996/test.zip)
